name: hello-world
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo "this is build!"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "this is test!"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "this is deploy!"
